# config.py

"""
Configuration file for the PubMed paper pipeline.
"""

JOURNAL_LIST = [
    "ACS Chemical Biology", 
    "ACS Synthetic Biology",
    "Annual Review of Microbiology",
    "Applied and Environmental Microbiology",
    "Bioinformatics",
    "Biotechnology and Bioengineering",
    "Briefings in Bioinformatics",
    "Cell",
    "Cell Chemical Biology",
    "Cell Reports",
    "Cell Systems",
    "Chemical Science",
    "Current Opinion in Biotechnology",
    "Metabolic Engineering",
    "Molecular Cell",
    "Nature",
    "Nature Biomedical Engineering",
    "Nature Biotechnology",
    "Nature Catalysis",
    "Nature Chemical Biology",
    "Nature Chemistry",
    "Nature Communications",
    "Nature Computational Science",
    "Nature Machine Intelligence",
    "Nature Metabolism",
    "Nature Methods",
    "Nature Microbiology",
    "Nature Reviews Molecular Cell Biology",
    "Nature Structural & Molecular Biology",
    "Nucleic Acids Research",
    "PLOS Biology",
    "PLOS Computational Biology",
    "PNAS",
    "Protein Science",
    "Science",
    "Science Advances",
    "Trends in Biochemical Sciences",
    "Trends in Biotechnology",
]
